In [132]:
import numpy as np

In [133]:
l = [1, 2, 3]
x = np.array(1)
x2 = np.array([1, 2, 3], dtype='f') 
x3 = np.array([1, 2, 3], dtype= np.int16)       # 권하는 형식

print(type(l), type(x))
print(x.dtype, x2.dtype, x3.dtype)

<class 'list'> <class 'numpy.ndarray'>
int64 float32 int16


In [134]:
a=np.array([1,2,3])
print(a, a.ndim)            # 몇 차원 데이터인지 확인

a = np.array([[1, 2], [3, 4]])
print(a, a.ndim)

[1 2 3] 1
[[1 2]
 [3 4]] 2


In [135]:
a=np.array([1, 2, 3, 4, 5], )
print (a, a.ndim)

a=np.array([1, 2, 3, 4, 5], ndmin=2)     # 어느 차원으로 만들지 지정  
print (a, a.ndim)

[1 2 3 4 5] 1
[[1 2 3 4 5]] 2


In [136]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print(a.shape)         # .shape 배열의 차수(행/열) 정보 : 읽기/쓰기 가능

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2)         # 3행 2열로 변환, 실제데이터는 그대로 유지, 읽어내고 제어하는 방식만 변화
print(a) 
print(a.shape)

a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2)      # 3행 2열로 변환해서 b에 저장, a는 바뀌지 않음, 원본은 두고 복사본 사용
print(b)
print(b.shape, a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2) (2, 3)


In [137]:
# a = np.array(range(24))     결과적으론 약간 다르나 동일함
a = np.arange(24)           # np.arange(i) 0 ~ (i-1) 까지 정수로 ndarray 만들기
print(a.ndim)
b = a.reshape(2,4,3) 
print(b.ndim)
print(b)

1
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [138]:
x = np.empty([3,2])     # 3행 2열로 만들며 비워둬라, 쓸모없는 값이 들어있을 수도 있다.
print(x)                # 사용빈도가 적다.

x = np.zeros((3,2))     # 3행 2열로 만들며 0으로 채워라
print(x)

x = np.ones([3,2])      # 3행 2열로 만들며 1로 채워라
print(x)

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [139]:
x = np.arange(10,21,2) 
print (x)


[10 12 14 16 18 20]


In [140]:
x = np.linspace(1,2,5, retstep = True) 
print (x) 

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), np.float64(0.25))


In [141]:
a = np.arange(10) 
b1 = a[2:7]
b2 = a[2:7:2]
print(a)
print(b1)
print(b2)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]


In [142]:
a = np.arange(10) 
b = a[5] 
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
5


In [143]:
a = np.arange(24)
a = a.reshape((4,6))
b = a.tolist()  #ndarry-> list 변환 2차원 이상으로 가면 단일명령으로 특정 행열을 가지고 오는방법은 없다

print(a)
b

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23]]

In [144]:
print(a[1:])
print(b[1:])


[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23]]


In [145]:
# 0행과 2행 데이터 조회
print(a[[0,2]])     # 인덱싱을 튜플 리스트로 
print([b[0],b[2]])

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]
[[0, 1, 2, 3, 4, 5], [12, 13, 14, 15, 16, 17]]


In [146]:
# 3열 데이터 조회
print(a[:,3])       # ndarray의 2차원 인덱싱->ar[row-indexing, col-indexing]
                    # ndarray의 2차원 슬라이싱 ->ar[row-slicing, col-slicing] 둘을 섞어 사용가능
print([v[3] for v in b ])  # 못함 


[ 3  9 15 21]
[3, 9, 15, 21]


In [147]:
print( a[:, [2,5]]) # 모든 행의 2열 , 5열 데이터 조회, 앞인덱싱 뒤 슬라이싱

[[ 2  5]
 [ 8 11]
 [14 17]
 [20 23]]


In [148]:
print(a[[1,3],:])   # 1, 3행의 모든 열 데이터 조회

[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]


In [149]:
# boolean indexing         True, False로 행과열을 값을 선택하도록 하는것이 가능
print(a)
#print(a[[True, False, True, True]]) 모든행에 자동으로됨
print(a[[True, False, True, True],:])               # 행에 True, False

print(a[:,[True, True, False, False, True, False]]) #열에 True, False
# print(a[:,[True, True, False, False]]) 오류 : boolean 리스트와 행 또는 열의 개수는 일치해야 한다

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  4]
 [ 6  7 10]
 [12 13 16]
 [18 19 22]]


In [150]:
# boolean indexing 4열의 데이터가 10보다 큰 모든 행을 뽑아라
print(a)
print( a[:, 4] >=10 ) # 4열의 값이 10 이상인지 여부

# print( b[0] > 3 ) 리스트와 단일값 연산 불가능   
 
# 4열의 값이 10 이상인 행 조회
# a[ a[:, 4] >= 10 ]  # 트루일때만 전체 뽑기 아주 자용 사용됨

mask =  a[:, 4] >= 10   # 한번 걸러서 사용 가능
a[ mask ]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[False  True  True  True]


array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [151]:
a1 = np.array([True, False, True])
b1 = np.array([True, False, False])

print(True and True)
print(True and False)
print(True or False)


# print(a and b)        # 오류 : and / or는 단일값에 대한 논리연산
print(a1 & b1)            # ndarray의 각 값에 대한 논리연산은 &, |

True
False
True
[ True False False]


In [152]:
# 전제 데이터 대상으로 짝수만 조회
print(a)
mask1 = a % 2 ==0
mask2 = a > 0 
mask3 = mask1 & mask2
#print(mask3)

a[mask3]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [ ]:
a2 = np.array([1,2,3,4]) 
b2 = np.array([10,20,30,40]) 
print(a2 + b2)                       # 두 ndarray를 더하면 요소별 연산 수행
print([1,2,3,4]+[10,20,30,40])  # 두 리스트를 더하면 리스트 결합


# 쌍이 맞지않을때 알아서 맞춤 없는 부분을 확장하여 처리
a3 = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b3 = np.array([1.0,2.0,3.0])
print (a3 + b3)

[11 22 33 44]
[1, 2, 3, 4, 10, 20, 30, 40]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
